---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: mawebappdeployment
spec:
 replicas: 1
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: mawebapp
 template:
  metadata:
   name: mawebapppod
   labels:
     app: mawebapp	 
  spec: 
    containers:
    - name: mawebappcontainer
      image: koteswarararaosairi/pavan
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: mawebappsvc
spec:
  type: NodePort
  selector:
   app: mawebapp
  ports:
   - port: 80
     targetPort: 8080
     nodePort: 30736
...
